let
    PUBLIC_FOLDERS_PORT = 37284;
    SSH_PORT = 15523;

    ALLOWED_UDP_PORTS = [];
    ALLOWED_TCP_PORTS = [ PUBLIC_FOLDERS_PORT 23841 ];

    NGINX_PROXY_MANAGER_PORTS = [ 80 18581 443 ];
in {
    inherit SSH_PORT;
    ADMIN_EMAIL = "vantrong2007vn@gmail.com";
    SERVER = {
        PUBLIC_FOLDERS = {
            PATH = "/home/PUBLIC";
            PORT = PUBLIC_FOLDERS_PORT;
        };
        ALLOWED_UDP_PORTS = ALLOWED_UDP_PORTS ++ [ ];
        ALLOWED_TCP_PORTS = ALLOWED_TCP_PORTS ++ NGINX_PROXY_MANAGER_PORTS ++ [ SSH_PORT  ];
    };
}