# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/fb43e44d-0d8f-4489-bc19-be832d0077de";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0FDA-6597";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/mnt/windows" =
  { device = "/dev/disk/by-uuid/0000294D000006E6";
    fsType = "ntfs-3g";
    options = [ "rw" "uid=1000" "gid=100" "umask=022" ];
  };

  fileSystems."/mnt/waydroid" = {
    device = "/home/asakiyuki/.local/share/waydroid/data/media/0";
    fsType = "fuse.bindfs";
    options = [
      "mirror=1000"
      "xattr-none"
      "chmod-ignore"
    ];
  };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/51cd0349-f54a-4faf-a5a2-c0372d530b3d"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
