name: "Check NixOS Flake"

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Check Flake Syntax & Outputs
        run: nix flake check

      - name: Check Formatting
        run: nix fmt -- --check

      - name: Dry-build NixOS Configuration
        run: nix eval .#nixosConfigurations --apply 'builtins.attrNames'
