name: nix flake update check

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NIX_CONFIG: "access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}"

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check flake inputs
        uses: DeterminateSystems/flake-checker-action@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Check for update and perform update
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          nix flake update --flake ./flakes/overlays
          cp flakes/overlays/flake.lock flakes/cursors/flake.lock
          cp flakes/overlays/flake.lock flakes/proton/flake.lock
          nix flake update

          git add flake.lock flakes/overlays/flake.lock flakes/cursors/flake.lock flakes/proton/flake.lock
          if ! git diff --cached --quiet; then
            git commit -m "ci(flake.lock): update flake inputs $(date '+%H:%M:%S %d-%m-%Y')"
          else
            echo "No changes in lock files to commit."
          fi

          git pull --rebase origin ${{ github.ref_name }}
          git push origin HEAD:${{ github.ref_name }}
