name: Update lock files

on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check flake inputs
        uses: DeterminateSystems/flake-checker-action@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Check for update and perform update
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Cập nhật lockfiles
          nix flake update
          cd flakes/overlays && nix flake update && cd ../..

          # Stage các file lock cụ thể
          git add flake.lock flakes/overlays/flake.lock

          # Kiểm tra xem có thay đổi không, nếu có mới commit và push
          if ! git diff --cached --quiet; then
            git commit -m "chore: update flake lockfiles"
            git push origin HEAD:${{ github.ref_name }}
          else
            echo "No changes in lock files to commit."
          fi
