name: Update lock files

on:
  schedule:
    - cron: "0 17 * * *"

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check flake inputs
        uses: DeterminateSystems/flake-checker-action@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Check for update and perform update
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          nix flake update
          cd flakes/overlays && nix flake update && cd ../..

          git add flake.lock flakes/overlays/flake.lock
          git diff --cached --exit-code || git commit -m "Update lock files"
          git push origin HEAD:main
