name: checking update

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check flake inputs
        uses: DeterminateSystems/flake-checker-action@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Check for update and perform update
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          nix flake update --flake ./flakes/overlays
          cp flakes/overlays/flake.lock flakes/cursors/flake.lock
          nix flake update

          git add flake.lock flakes/overlays/flake.lock flakes/cursors/flake.lock
          if ! git diff --cached --quiet; then
            git commit -m "ci(flake.lock): update flake inputs $(date '+%H:%M:%S %d-%m-%Y')"
          else
            echo "No changes in lock files to commit."
          fi

          bun run check-package-updates || true

          git add assets/packages.json
          if ! git diff --cached --quiet; then
            git commit -m "ci(assets/packages.json): update packages infos $(date '+%H:%M:%S %d-%m-%Y')"
          else
            echo "No changes in packages files to commit."
          fi

          git pull --rebase origin ${{ github.ref_name }}
          git push origin HEAD:${{ github.ref_name }}
